# Generated by Django 5.1.7 on 2025-04-07 11:03

import clients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_birthday_alter_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True, validators=[clients.validators.validate_email], verbose_name='эл. почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[clients.validators.validate_username], verbose_name='никнейм'),
        ),
    ]
